# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2d7e5481a9e5b83944e77972d5b40e96"
name = "Share Basket"
handle = "share-basket"
application_url = "https://sharebasket.winsomies.com/"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]
  uri = "/webhooks"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_metaobjects,write_metaobject_definitions,write_metaobjects,write_products,write_themes,read_discounts"

[auth]
redirect_urls = [
  "https://sharebasket.winsomies.com//auth/callback",
  "https://sharebasket.winsomies.com//auth/shopify/callback",
  "https://sharebasket.winsomies.com//api/auth/callback"
]

[pos]
embedded = false
